name: python-002

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/python_002.yml'
      - 'projects/python/002/**'
  workflow_dispatch:

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r projects/python/002/requirements.txt

      - name: Run pytest
        working-directory: projects/python/002
        run: |
          pytest --cov=source --cov-report=html --cov-report=term > coverage.txt

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: projects/python/002/htmlcov

      - name: Setup Ruby, JRuby and TruffleRuby
        if: github.event_name == 'pull_request'
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      - name: Cache Ruby gems
        uses: actions/cache@v4
        if: github.event_name == 'pull_request'
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('ci/python_002/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-${{ hashFiles('ci/python_002/Gemfile.lock') }}
            ${{ runner.os }}-gems-${{ hashFiles('ci/python_002/Gemfile') }}
            ${{ runner.os }}-gems-

      - name: Run Danger
        uses: MeilCli/danger-action@v6
        if: github.event_name == 'pull_request'
        with:
          plugins_file: 'ci/python_002/Gemfile'
          install_path: 'vendor/bundle'
          danger_file: 'ci/python_002/Dangerfile'
          danger_id: 'danger-pr-python_002'
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
